Added a test for rest/providers/list_app.py and wrapepd said list_all.py's web.header() function in a try-catch block
CyberReboot/vcontrol pull request #115
Opened 2016-10-27 21:36 UTC by Enether

#101

2016-10-27 21:42 UTC, Enether commented
Please check out codeclimate's issues and instruct me further

2016-10-27 21:46 UTC, cglewis commented
note the following lines that are still not tested (21-23, 25-26):
```
/vcontrol/vcontrol/rest/providers/list_all.py             19      5    74%   21-23, 25-26
```

2016-10-28 01:07 UTC, cglewis commented
@Enether i think the complexity issues that codeclimate are complaining about were already there, but are showing up because you're changing code in that function/class.  going to ignore that for now, but should probably be something addressed in a different issue.

2016-10-29 21:57 UTC, Enether commented
@cglewis I think this new modification should get lines 21-23. Although I don't know how to cover 25-26, because they're the except clause of `with open('providers.txt', 'r') as f:`

2016-10-29 22:01 UTC, cglewis requested changes

2016-10-29 22:01 UTC, cglewis commented on vcontrol/rest/providers/providers.txt
> +TEST : TEST
I'd rather not have this included in the repo, but instead have the test create this file for testing, and then clean up after itself after the test runs.

2016-10-29 22:02 UTC, cglewis commented
regarding the coverage, for lines 25-26, i think it can be triggered by having a malformed line in the `providers.txt`, for example something without a `:` will throw the exception due to an index out of bounds error.

2016-10-29 23:35 UTC, Enether commented
Okay we should be good now :)

2016-10-30 00:19 UTC, cglewis commented on vcontrol/rest/providers/list_all.py
> +            if os.path.isfile(providers_file_path):
both of the asserts that are failing show that the output of `GET()` is `{}` which means that it's passing through this if statement and just returning `providers` as `{}`, so think that means that the path doesn't exist on the test framework.  somehow the way you're creating it with relative paths is not the same on circleci as how you're running it locally.

2016-10-30 19:16 UTC, cglewis approved these changes

2016-10-30 19:16 UTC, merged

2016-10-30 19:16 UTC, cglewis commented
thanks!